# 指定端口以及访问路径
server:
  port: 8330
  servlet:
    context-path: /url-manager

# mysql 相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://47.93.225.12:13306/meetting-manager?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8&autoReconnect=true
    username: -----
    password: -----

  # jpa 相关配置自动建表：update 没有表新建，有表更新操作,控制台显示建表语句 database-platform 表示指定表默认引擎
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: update
